//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using PackageTracker.WebServices;

namespace FedExRegistrationApi
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fedex.com/ws/registration/v7", ConfigurationName="RegistrationPortType")]
    public interface RegistrationPortType
    {      
        [System.ServiceModel.OperationContractAttribute(Action="http://fedex.com/ws/registration/v7/registerWebUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<registerWebUserResponse> registerWebUserAsync(registerWebUserRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fedex.com/ws/registration/v7/versionCapture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<versionCaptureResponse> versionCaptureAsync(versionCaptureRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fedex.com/ws/registration/v7/subscription", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<subscriptionResponse> subscriptionAsync(subscriptionRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class RegisterWebUserRequest
    {
        
        private WebAuthenticationDetail webAuthenticationDetailField;
        
        private ClientDetail clientDetailField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private WebAuthenticationCredential parentCredentialField;
        
        private WebServiceCategoryType[] categoriesField;
        
        private Address shippingAddressField;
        
        private ParsedContactAndAddress userContactAndAddressField;
        
        private string secondaryEmailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public WebAuthenticationDetail WebAuthenticationDetail
        {
            get
            {
                return this.webAuthenticationDetailField;
            }
            set
            {
                this.webAuthenticationDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ClientDetail ClientDetail
        {
            get
            {
                return this.clientDetailField;
            }
            set
            {
                this.clientDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TransactionDetail TransactionDetail
        {
            get
            {
                return this.transactionDetailField;
            }
            set
            {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public VersionId Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public WebAuthenticationCredential ParentCredential
        {
            get
            {
                return this.parentCredentialField;
            }
            set
            {
                this.parentCredentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Categories", Order=5)]
        public WebServiceCategoryType[] Categories
        {
            get
            {
                return this.categoriesField;
            }
            set
            {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Address ShippingAddress
        {
            get
            {
                return this.shippingAddressField;
            }
            set
            {
                this.shippingAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ParsedContactAndAddress UserContactAndAddress
        {
            get
            {
                return this.userContactAndAddressField;
            }
            set
            {
                this.userContactAndAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SecondaryEmail
        {
            get
            {
                return this.secondaryEmailField;
            }
            set
            {
                this.secondaryEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class WebAuthenticationDetail
    {
        
        private WebAuthenticationCredential parentCredentialField;
        
        private WebAuthenticationCredential userCredentialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public WebAuthenticationCredential ParentCredential
        {
            get
            {
                return this.parentCredentialField;
            }
            set
            {
                this.parentCredentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public WebAuthenticationCredential UserCredential
        {
            get
            {
                return this.userCredentialField;
            }
            set
            {
                this.userCredentialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class WebAuthenticationCredential
    {
        
        private string keyField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class MeterDetail
    {
        
        private string meterNumberField;
        
        private string groundShipperNumberField;
        
        private string epdiCodeField;
        
        private System.DateTime reconcileTimeField;
        
        private bool reconcileTimeFieldSpecified;
        
        private string groundTrackingNumberStartField;
        
        private string groundTrackingNumberEndField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MeterNumber
        {
            get
            {
                return this.meterNumberField;
            }
            set
            {
                this.meterNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GroundShipperNumber
        {
            get
            {
                return this.groundShipperNumberField;
            }
            set
            {
                this.groundShipperNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EpdiCode
        {
            get
            {
                return this.epdiCodeField;
            }
            set
            {
                this.epdiCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=3)]
        public System.DateTime ReconcileTime
        {
            get
            {
                return this.reconcileTimeField;
            }
            set
            {
                this.reconcileTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReconcileTimeSpecified
        {
            get
            {
                return this.reconcileTimeFieldSpecified;
            }
            set
            {
                this.reconcileTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string GroundTrackingNumberStart
        {
            get
            {
                return this.groundTrackingNumberStartField;
            }
            set
            {
                this.groundTrackingNumberStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string GroundTrackingNumberEnd
        {
            get
            {
                return this.groundTrackingNumberEndField;
            }
            set
            {
                this.groundTrackingNumberEndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class SubscriptionReply
    {
        
        private NotificationSeverityType highestSeverityField;
        
        private bool highestSeverityFieldSpecified;
        
        private Notification[] notificationsField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private MeterDetail meterDetailField;
        
        private SubscriptionServiceType[] registeredServicesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NotificationSeverityType HighestSeverity
        {
            get
            {
                return this.highestSeverityField;
            }
            set
            {
                this.highestSeverityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HighestSeveritySpecified
        {
            get
            {
                return this.highestSeverityFieldSpecified;
            }
            set
            {
                this.highestSeverityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Notifications", Order=1)]
        public Notification[] Notifications
        {
            get
            {
                return this.notificationsField;
            }
            set
            {
                this.notificationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TransactionDetail TransactionDetail
        {
            get
            {
                return this.transactionDetailField;
            }
            set
            {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public VersionId Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public MeterDetail MeterDetail
        {
            get
            {
                return this.meterDetailField;
            }
            set
            {
                this.meterDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RegisteredServices", Order=5)]
        public SubscriptionServiceType[] RegisteredServices
        {
            get
            {
                return this.registeredServicesField;
            }
            set
            {
                this.registeredServicesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public enum NotificationSeverityType
    {
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        FAILURE,
        
        /// <remarks/>
        NOTE,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        WARNING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class Notification
    {
        
        private NotificationSeverityType severityField;
        
        private bool severityFieldSpecified;
        
        private string sourceField;
        
        private string codeField;
        
        private string messageField;
        
        private string localizedMessageField;
        
        private NotificationParameter[] messageParametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NotificationSeverityType Severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SeveritySpecified
        {
            get
            {
                return this.severityFieldSpecified;
            }
            set
            {
                this.severityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LocalizedMessage
        {
            get
            {
                return this.localizedMessageField;
            }
            set
            {
                this.localizedMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MessageParameters", Order=5)]
        public NotificationParameter[] MessageParameters
        {
            get
            {
                return this.messageParametersField;
            }
            set
            {
                this.messageParametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class NotificationParameter
    {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class TransactionDetail
    {
        
        private string customerTransactionIdField;
        
        private Localization localizationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerTransactionId
        {
            get
            {
                return this.customerTransactionIdField;
            }
            set
            {
                this.customerTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Localization Localization
        {
            get
            {
                return this.localizationField;
            }
            set
            {
                this.localizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class Localization
    {
        
        private string languageCodeField;
        
        private string localeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LanguageCode
        {
            get
            {
                return this.languageCodeField;
            }
            set
            {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LocaleCode
        {
            get
            {
                return this.localeCodeField;
            }
            set
            {
                this.localeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class VersionId
    {
        
        private string serviceIdField;
        
        private int majorField;
        
        private int intermediateField;
        
        private int minorField;
        
        public VersionId()
        {
            this.serviceIdField = "fcas";
            this.majorField = 7;
            this.intermediateField = 0;
            this.minorField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Major
        {
            get
            {
                return this.majorField;
            }
            set
            {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Intermediate
        {
            get
            {
                return this.intermediateField;
            }
            set
            {
                this.intermediateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Minor
        {
            get
            {
                return this.minorField;
            }
            set
            {
                this.minorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public enum SubscriptionServiceType
    {
        
        /// <remarks/>
        EXPRESS_SHIPPING,
        
        /// <remarks/>
        GROUND_SHIPPING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class Contact
    {
        
        private string personNameField;
        
        private string companyNameField;
        
        private string phoneNumberField;
        
        private string phoneExtensionField;
        
        private string tollFreePhoneNumberField;
        
        private string pagerNumberField;
        
        private string faxNumberField;
        
        private string eMailAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PersonName
        {
            get
            {
                return this.personNameField;
            }
            set
            {
                this.personNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PhoneExtension
        {
            get
            {
                return this.phoneExtensionField;
            }
            set
            {
                this.phoneExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TollFreePhoneNumber
        {
            get
            {
                return this.tollFreePhoneNumberField;
            }
            set
            {
                this.tollFreePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PagerNumber
        {
            get
            {
                return this.pagerNumberField;
            }
            set
            {
                this.pagerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FaxNumber
        {
            get
            {
                return this.faxNumberField;
            }
            set
            {
                this.faxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string EMailAddress
        {
            get
            {
                return this.eMailAddressField;
            }
            set
            {
                this.eMailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class Party
    {
        
        private string accountNumberField;
        
        private Contact contactField;
        
        private Address addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Contact Contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Address Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class Address
    {
        
        private string[] streetLinesField;
        
        private string cityField;
        
        private string stateOrProvinceCodeField;
        
        private string postalCodeField;
        
        private string countryCodeField;
        
        private string countryNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StreetLines", Order=0)]
        public string[] StreetLines
        {
            get
            {
                return this.streetLinesField;
            }
            set
            {
                this.streetLinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StateOrProvinceCode
        {
            get
            {
                return this.stateOrProvinceCodeField;
            }
            set
            {
                this.stateOrProvinceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CountryName
        {
            get
            {
                return this.countryNameField;
            }
            set
            {
                this.countryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class SubscriptionRequest
    {
        
        private WebAuthenticationDetail webAuthenticationDetailField;
        
        private ClientDetail clientDetailField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private string cspSolutionIdField;
        
        private CspType cspTypeField;
        
        private bool cspTypeFieldSpecified;
        
        private Party subscriberField;
        
        private Address accountShippingAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public WebAuthenticationDetail WebAuthenticationDetail
        {
            get
            {
                return this.webAuthenticationDetailField;
            }
            set
            {
                this.webAuthenticationDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ClientDetail ClientDetail
        {
            get
            {
                return this.clientDetailField;
            }
            set
            {
                this.clientDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TransactionDetail TransactionDetail
        {
            get
            {
                return this.transactionDetailField;
            }
            set
            {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public VersionId Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CspSolutionId
        {
            get
            {
                return this.cspSolutionIdField;
            }
            set
            {
                this.cspSolutionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public CspType CspType
        {
            get
            {
                return this.cspTypeField;
            }
            set
            {
                this.cspTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CspTypeSpecified
        {
            get
            {
                return this.cspTypeFieldSpecified;
            }
            set
            {
                this.cspTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Party Subscriber
        {
            get
            {
                return this.subscriberField;
            }
            set
            {
                this.subscriberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Address AccountShippingAddress
        {
            get
            {
                return this.accountShippingAddressField;
            }
            set
            {
                this.accountShippingAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class ClientDetail
    {
        
        private string accountNumberField;
        
        private string meterNumberField;
        
        private string integratorIdField;
        
        private ExpressRegionCode regionField;
        
        private bool regionFieldSpecified;
        
        private Localization localizationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MeterNumber
        {
            get
            {
                return this.meterNumberField;
            }
            set
            {
                this.meterNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IntegratorId
        {
            get
            {
                return this.integratorIdField;
            }
            set
            {
                this.integratorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ExpressRegionCode Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegionSpecified
        {
            get
            {
                return this.regionFieldSpecified;
            }
            set
            {
                this.regionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Localization Localization
        {
            get
            {
                return this.localizationField;
            }
            set
            {
                this.localizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public enum ExpressRegionCode
    {
        
        /// <remarks/>
        APAC,
        
        /// <remarks/>
        CA,
        
        /// <remarks/>
        EMEA,
        
        /// <remarks/>
        LAC,
        
        /// <remarks/>
        US,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public enum CspType
    {
        
        /// <remarks/>
        CERTIFIED_SOLUTION_PROVIDER,
        
        /// <remarks/>
        HTML_WEB_SERVICES_TOOL,
        
        /// <remarks/>
        TRADITIONAL_API,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class VersionCaptureReply
    {
        
        private NotificationSeverityType highestSeverityField;
        
        private bool highestSeverityFieldSpecified;
        
        private Notification[] notificationsField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NotificationSeverityType HighestSeverity
        {
            get
            {
                return this.highestSeverityField;
            }
            set
            {
                this.highestSeverityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HighestSeveritySpecified
        {
            get
            {
                return this.highestSeverityFieldSpecified;
            }
            set
            {
                this.highestSeverityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Notifications", Order=1)]
        public Notification[] Notifications
        {
            get
            {
                return this.notificationsField;
            }
            set
            {
                this.notificationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TransactionDetail TransactionDetail
        {
            get
            {
                return this.transactionDetailField;
            }
            set
            {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public VersionId Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class VersionCaptureRequest
    {
        
        private WebAuthenticationDetail webAuthenticationDetailField;
        
        private ClientDetail clientDetailField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private string originLocationIdField;
        
        private string vendorProductPlatformField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public WebAuthenticationDetail WebAuthenticationDetail
        {
            get
            {
                return this.webAuthenticationDetailField;
            }
            set
            {
                this.webAuthenticationDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ClientDetail ClientDetail
        {
            get
            {
                return this.clientDetailField;
            }
            set
            {
                this.clientDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TransactionDetail TransactionDetail
        {
            get
            {
                return this.transactionDetailField;
            }
            set
            {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public VersionId Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OriginLocationId
        {
            get
            {
                return this.originLocationIdField;
            }
            set
            {
                this.originLocationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string VendorProductPlatform
        {
            get
            {
                return this.vendorProductPlatformField;
            }
            set
            {
                this.vendorProductPlatformField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class RegisterWebUserReply
    {
        
        private NotificationSeverityType highestSeverityField;
        
        private bool highestSeverityFieldSpecified;
        
        private Notification[] notificationsField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private WebAuthenticationCredential userCredentialField;
        
        private string clientProductIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NotificationSeverityType HighestSeverity
        {
            get
            {
                return this.highestSeverityField;
            }
            set
            {
                this.highestSeverityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HighestSeveritySpecified
        {
            get
            {
                return this.highestSeverityFieldSpecified;
            }
            set
            {
                this.highestSeverityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Notifications", Order=1)]
        public Notification[] Notifications
        {
            get
            {
                return this.notificationsField;
            }
            set
            {
                this.notificationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TransactionDetail TransactionDetail
        {
            get
            {
                return this.transactionDetailField;
            }
            set
            {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public VersionId Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public WebAuthenticationCredential UserCredential
        {
            get
            {
                return this.userCredentialField;
            }
            set
            {
                this.userCredentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ClientProductId
        {
            get
            {
                return this.clientProductIdField;
            }
            set
            {
                this.clientProductIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class ParsedPersonName
    {
        
        private string prefixField;
        
        private string titleField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string lastNameField;
        
        private string suffixField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Prefix
        {
            get
            {
                return this.prefixField;
            }
            set
            {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MiddleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Suffix
        {
            get
            {
                return this.suffixField;
            }
            set
            {
                this.suffixField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class ParsedContact
    {
        
        private ParsedPersonName personNameField;
        
        private string titleField;
        
        private string companyNameField;
        
        private string phoneNumberCountryCodeField;
        
        private string phoneNumberAreaCodeField;
        
        private string phoneNumberField;
        
        private string phoneExtensionField;
        
        private string pagerNumberField;
        
        private string faxNumberField;
        
        private string eMailAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ParsedPersonName PersonName
        {
            get
            {
                return this.personNameField;
            }
            set
            {
                this.personNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PhoneNumberCountryCode
        {
            get
            {
                return this.phoneNumberCountryCodeField;
            }
            set
            {
                this.phoneNumberCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PhoneNumberAreaCode
        {
            get
            {
                return this.phoneNumberAreaCodeField;
            }
            set
            {
                this.phoneNumberAreaCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PhoneExtension
        {
            get
            {
                return this.phoneExtensionField;
            }
            set
            {
                this.phoneExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PagerNumber
        {
            get
            {
                return this.pagerNumberField;
            }
            set
            {
                this.pagerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FaxNumber
        {
            get
            {
                return this.faxNumberField;
            }
            set
            {
                this.faxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EMailAddress
        {
            get
            {
                return this.eMailAddressField;
            }
            set
            {
                this.eMailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public partial class ParsedContactAndAddress
    {
        
        private ParsedContact contactField;
        
        private Address addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ParsedContact Contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Address Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/registration/v7")]
    public enum WebServiceCategoryType
    {
        
        /// <remarks/>
        OFFICE_AND_PRINT,
        
        /// <remarks/>
        SHIPPING,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerWebUserRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fedex.com/ws/registration/v7", Order=0)]
        public RegisterWebUserRequest RegisterWebUserRequest;
        
        public registerWebUserRequest1()
        {
        }
        
        public registerWebUserRequest1(RegisterWebUserRequest RegisterWebUserRequest)
        {
            this.RegisterWebUserRequest = RegisterWebUserRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerWebUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fedex.com/ws/registration/v7", Order=0)]
        public RegisterWebUserReply RegisterWebUserReply;
        
        public registerWebUserResponse()
        {
        }
        
        public registerWebUserResponse(RegisterWebUserReply RegisterWebUserReply)
        {
            this.RegisterWebUserReply = RegisterWebUserReply;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class versionCaptureRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fedex.com/ws/registration/v7", Order=0)]
        public VersionCaptureRequest VersionCaptureRequest;
        
        public versionCaptureRequest1()
        {
        }
        
        public versionCaptureRequest1(VersionCaptureRequest VersionCaptureRequest)
        {
            this.VersionCaptureRequest = VersionCaptureRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class versionCaptureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fedex.com/ws/registration/v7", Order=0)]
        public VersionCaptureReply VersionCaptureReply;
        
        public versionCaptureResponse()
        {
        }
        
        public versionCaptureResponse(VersionCaptureReply VersionCaptureReply)
        {
            this.VersionCaptureReply = VersionCaptureReply;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class subscriptionRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fedex.com/ws/registration/v7", Order=0)]
        public SubscriptionRequest SubscriptionRequest;
        
        public subscriptionRequest1()
        {
        }
        
        public subscriptionRequest1(SubscriptionRequest SubscriptionRequest)
        {
            this.SubscriptionRequest = SubscriptionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class subscriptionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fedex.com/ws/registration/v7", Order=0)]
        public SubscriptionReply SubscriptionReply;
        
        public subscriptionResponse()
        {
        }
        
        public subscriptionResponse(SubscriptionReply SubscriptionReply)
        {
            this.SubscriptionReply = SubscriptionReply;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface RegistrationPortTypeChannel : RegistrationPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class RegistrationPortTypeClient : System.ServiceModel.ClientBase<RegistrationPortType>, RegistrationPortType, IFedExRegistrationClient
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RegistrationPortTypeClient() : 
                base(RegistrationPortTypeClient.GetDefaultBinding(), RegistrationPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RegistrationServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RegistrationPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(RegistrationPortTypeClient.GetBindingForEndpoint(endpointConfiguration), RegistrationPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RegistrationPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RegistrationPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RegistrationPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RegistrationPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RegistrationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<registerWebUserResponse> RegistrationPortType.registerWebUserAsync(registerWebUserRequest1 request)
        {
            return base.Channel.registerWebUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<registerWebUserResponse> registerWebUserAsync(RegisterWebUserRequest RegisterWebUserRequest)
        {
            registerWebUserRequest1 inValue = new registerWebUserRequest1();
            inValue.RegisterWebUserRequest = RegisterWebUserRequest;
            return ((RegistrationPortType)(this)).registerWebUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<versionCaptureResponse> RegistrationPortType.versionCaptureAsync(versionCaptureRequest1 request)
        {
            return base.Channel.versionCaptureAsync(request);
        }
        
        public System.Threading.Tasks.Task<versionCaptureResponse> versionCaptureAsync(VersionCaptureRequest VersionCaptureRequest)
        {
            versionCaptureRequest1 inValue = new versionCaptureRequest1();
            inValue.VersionCaptureRequest = VersionCaptureRequest;
            return ((RegistrationPortType)(this)).versionCaptureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<subscriptionResponse> RegistrationPortType.subscriptionAsync(subscriptionRequest1 request)
        {
            return base.Channel.subscriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<subscriptionResponse> subscriptionAsync(SubscriptionRequest SubscriptionRequest)
        {
            subscriptionRequest1 inValue = new subscriptionRequest1();
            inValue.SubscriptionRequest = SubscriptionRequest;
            return ((RegistrationPortType)(this)).subscriptionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RegistrationServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RegistrationServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://wsbeta.fedex.com/web-services");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RegistrationPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.RegistrationServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RegistrationPortTypeClient.GetEndpointAddress(EndpointConfiguration.RegistrationServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            RegistrationServicePort,
        }
    }
}
